
---
- name: Install default Apache Web Server
  hosts: all
  become: yes

  vars:
    source_folder: ./mywebpage
    destin_folder: /var/www/html

  tasks:
 
  - name: Check and print linux version
    debug: var=ansible_os_family

  - block:   # Block for RedHAt

      - name: Install Apache WebServer for RedHat
        yum: name=httpd state=latest

      - name: Start Web Server service for RedHat
        service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"
    
    
    
  - block:  # block for Debian

      - name: Install Apache WebServer for Debian
        apt: name=apache2 state=latest

      - name: Start Web Server service for Debian
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

   
  - name: Copy and Synchronization WebPage to Servers
    synchronize:
      src= {{ source_folder }} 
      dest= {{ destin_folder }}

    notify:
       - Restart Apache RedHat
       - Restart Apache Debian 
 

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"

